### ISSUE TITLE
VPN privacy concerns. (PIA - Private Internet Access)

### ISSUE THREAD

**Issue by frankpanduh** [Igglybuff/awesome-piracy#587] opened 2021-10-30 03:09 UTC
PIA (Private Internet Access) is owned by "Kape Technologies" (formerly Crossrider). 

Sources:
https://restoreprivacy.com/kape-technologies-owns-expressvpn-cyberghost-pia-zenmate-vpn-review-sites/

https://torrentfreak.com/private-internet-access-to-be-acquired-by-kape/

https://torrentfreak.com/private-internet-access-to-be-acquired-by-kape/amp/

**Comment by Shakil-Shahadat** [comment] 2021-10-30 03:25
Dupe of #233

**Closed** 2023-06-18 22:07 UTC
