### ISSUE TITLE
Update PIA "star status" they got sold out

### ISSUE THREAD

**Issue by dmxt** [Igglybuff/awesome-piracy#258] opened 2020-02-23 19:58 UTC
They got bought by a corp who also bought 3 other vpns and earlier in the 2010s it was the same company that used malware for monetization. There's all-out discussion regarding this issue.

**Comment by Igglybuff** [comment] 2020-04-12 22:49
Dupe of #233

**Closed by Igglybuff** 2020-04-12 22:49 UTC
